# deepcode.yml configuration file for the API repository
version: 1.0
api:
  name: DeepCodeAPI
  description: "API for triggering deep code analysis, powered by LLM integration"
  base_url: "https://api.deepcode.com"
  routes:
    analyze_code: "/analyze"  # POST request to trigger code analysis
    get_status: "/status"      # GET request to check the status of an analysis

settings:
  analysis_level: full   # Full analysis of code on request
  supported_languages:
    - python
    - javascript
    - java
    - go
    - typescript
  auto_trigger_on_push: true # Automatically trigger analysis on code push

llm_integration:
  enabled: true
  model_name: "gpt-4"  # Model for providing code suggestions
  api_url: "https://api.openai.com/v1/completions"  # URL for the LLM API
  prompt_template: |
    "Analyze the following code and provide recommendations for security, performance, and code quality improvements:\n
    {code}"

security_analysis:
  enabled: true
  rules:
    - SQL Injection
    - Cross-Site Scripting (XSS)
    - Insecure Dependencies
    - Secrets in Code

performance_analysis:
  enabled: true
  rules:
    - Memory Leaks
    - Inefficient Loops
    - Unnecessary Computation

notifications:
  email:
    enabled: true
    recipients:
      - "your-email@example.com"
  slack:
    enabled: true
    webhook_url: "https://hooks.slack.com/services/your/slack/webhook"

logging:
  level: info
  log_file: "/logs/deepcode_api.log"
