name: DeepCode Analysis

on:
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main  # Trigger on push to the main branch
    paths:
      - '**/*.py'    # Adjust to your file types (e.g., Python files)
      - '**/*.js'    # JavaScript files
      - '**/*.ts'    # TypeScript files
      - '**/*.java'  # Java files
      - '**/*.go'    # Go files

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment (if using Python for backend)
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Change to your preferred Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install your dependencies (if needed)

      - name: Run code analysis API (via POST request)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # LLM API Key stored in GitHub secrets
        run: |
          curl -X POST "https://api.deepcode.com/analyze" \
            -H "Content-Type: application/json" \
            -d '{
                  "language": "python",  # Adjust based on the file being analyzed
                  "code": "$(cat my_script.py)"  # Provide the code to analyze
                }'

      - name: Save Analysis Logs
        run: |
          curl -X POST "https://slack.com/api/chat.postMessage" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.SLACK_API_TOKEN }}" \
            --data '{
              "channel": "#your-channel",
              "text": "Code analysis completed. Please check the results."
            }'

  notify:
    runs-on: ubuntu-latest
    needs: analysis
    steps:
      - name: Notify result on Slack
        uses: slackapi/slack-github-action@v1
        with:
          slack-token: ${{ secrets.SLACK_API_TOKEN }}
          channel-id: '#your-channel'
          text: 'Code analysis has finished successfully! Check the logs for more details.'
